inc/shortcodes/class-shortcode.php
This will let implementers locally scope their shortcodes
=> Add filter to shortcode tag

Gruntfile.js, phpcs.ruleset.xml
=> Use our own PHPCS ruleset

inc/shortcodes/class-infogram.php
=> Escape Infogram `$id` for security

inc/shortcodes/class-rap-genius.php
=> Escape periods because dot matches all in regex

assets/js/shortcake-bakery.js, inc/class-shortcake-bakery.php, inc/shortcodes/class-facebook.php, shortcake-bakery.php, tests/test-facebook-shortcode.php
=> Responsive Facebook posts and videos

.editorconfig
Added .editorconfig file to automate standardizing some coding style guidelines at the editor level.
=> Added .editorconfig file.

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/13
=> Improve support for Facebook permalinks

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/13
=> 13 improve photo handling

assets/images/svg/icon-playbuzz.svg, inc/class-shortcake-bakery.php, inc/shortcodes/class-playbuzz.php, tests/test-playbuzz-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/45
=> Migrate Playbuzz to Shortcake Bakery

inc/shortcodes/class-playbuzz.php
=> Use the Playbuzz icon for Playbuzz, not Scribd

inc/shortcodes/class-scribd.php, tests/test-scribd-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/7
=> Make Scribd iframe responsive

inc/class-shortcake-bakery.php, inc/shortcodes/class-script.php, tests/test-script-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/42
Related: https://github.com/fusioneng/fusion-theme/pull/3422
=> Migrate script shortcake and add whitelist filter

inc/shortcodes/class-image-comparision.php
=> Fix script reference for juxtapose.js

inc/class-shortcake-bakery.php, inc/shortcodes/class-image-comparison.php, tests/test-image-comparison.php
=> Correctly spell "Comparison"

inc/class-shortcake-bakery.php, inc/shortcodes/class-facebook.php
See https://github.com/fusioneng/shortcake-bakery/issues/59
=> Output facebook script in admin

inc/shortcodes/class-pdf.php, tests/test-pdf-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/58
=> Load PDF.js with appropriate scheme

inc/shortcodes/class-iframe.php, tests/test-iframe-shortcode.php
https://twitter.com/evilgaywitch/status/623905861946093568
=> Fix responsiveness in iframe shortcode

inc/shortcodes/class-iframe.php
See https://github.com/fusioneng/shortcake-bakery/issues/71
=> Fix mismatch between default and description

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
See https://fusionnetwork.slack.com/archives/tech/p1438795785002079
=> Hotfix for new style FB video URL's

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
=> Support for Facebook Group permalinks

inc/shortcodes/class-videoo.php
=> Prevent Videoo from breaking outside of bounds on iPhone6

inc/class-shortcake-bakery.php
See https://github.com/fusioneng/Shortcake/issues/448
=> Fix scope issues where `$this` isn't supported inside of closures

assets/images/svg/icon-instagram.svg, inc/class-shortcake-bakery.php, inc/shortcodes/class-instagram.php, inc/shortcodes/class-vimeo.php, tests/test-instagram-shortcode.php, tests/test-vimeo-shortcode.php
=> Add Vimeo and Instagram shortcodes with reversals

inc/shortcodes/class-facebook.php, inc/shortcodes/class-giphy.php, inc/shortcodes/class-infogram.php, inc/shortcodes/class-instagram.php, inc/shortcodes/class-playbuzz.php, inc/shortcodes/class-rap-genius.php, inc/shortcodes/class-scribd.php, inc/shortcodes/class-script.php, inc/shortcodes/class-twitter.php, inc/shortcodes/class-videoo.php, inc/shortcodes/class-vimeo.php, inc/shortcodes/class-vine.php
=> Prevent running regex unnecessarily on shortcode reversals

inc/shortcodes/class-shortcode.php, tests/test-shortcode.php
=> Improve parsing for attribute values containing spaces

inc/shortcodes/class-giphy.php, inc/shortcodes/class-shortcode.php, inc/shortcodes/class-vimeo.php, tests/bootstrap.php, tests/class-shortcode.php, tests/test-shortcode.php
This will help prevent duplicated regex everywhere
See #99
=> Create abstraction for reversing `<iframe>`

inc/shortcodes/class-iframe.php, tests/test-iframe-shortcode.php
=> Shortcode reversal for iframe shortcode

inc/shortcodes/class-scribd.php, tests/test-scribd-shortcode.php
It also catches more types of Scribd embeds
See #98
=> Migrate Scribd reversal to use `parse_iframes()` method

inc/shortcodes/class-youtube.php, tests/test-youtube-shortcode.php
This makes it easier for themes and plugins to modify the embed
=> Support filtering YouTube embed URL

inc/shortcodes/class-infogram.php, inc/shortcodes/class-instagram.php, inc/shortcodes/class-rap-genius.php, inc/shortcodes/class-script.php, inc/shortcodes/class-videoo.php, inc/shortcodes/class-vine.php, inc/shortcodes/class-youtube.php, tests/test-infogram-shortcode.php, tests/test-script-shortcode.php
=> Convert remaining shortcode reversals to use `parse_scripts()` and `parse_iframes()`

assets/images/svg/icon-flickr.svg, inc/class-shortcake-bakery.php, inc/shortcodes/class-flickr.php, tests/test-flickr-shortcode.php
=> Add shortcode and reversal for Flickr

inc/shortcodes/class-instagram.php, tests/test-instagram-shortcode.php
=> Reverse Instagram embeds when they're missing `<script>` at the end

inc/shortcodes/class-vine.php, phpcs.ruleset.xml, tests/test-vine-shortcode.php
=> Add embed type and autoplay audio options for Vine

inc/shortcodes/class-soundcloud.php, tests/test-soundcloud-shortcode.php
=> Add embed type and autoplay settings for Soundcloud

inc/shortcodes/class-silk.php, tests/test-silk-shortcode.php
=> Add height options to Silk shortcode

assets/js/shortcake-bakery.js
=> Persist original proportion when width and height are explicitly declared

inc/class-shortcake-bakery.php
=> Add filter to shortcode HTML output

inc/shortcodes/class-youtube.php, tests/test-youtube-shortcode.php
=> Properly parse YouTube shortcodes on preview

inc/shortcodes/class-giphy.php, tests/test-giphy-shortcode.php
=> Set better default proportions for Giphy embed; allow override h/w

inc/shortcodes/class-giphy.php, tests/test-giphy-shortcode.php
=> Handle Giphy urls without hyphenated slugs

inc/shortcodes/class-instagram.php, tests/test-instagram-shortcode.php
Allow for Instagram URLs matching www.instagram.com.
See #171
=> Update reversal pattern for Instagram version 6 embed code

inc/class-shortcake-bakery.php
=> Update filter reference for embed button

inc/shortcodes/class-infogram.php, tests/test-infogram-shortcode.php
A continuation of pull request #213; with all merge conflicts fixed against the
updated master. See issue #212.
=> Handle new infogram domain

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
Ability to embed Facebook photos in the following format:
https://www.facebook.com/photo.php?fbid=2089627184639065
=> Facebook photo embed
