inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
See https://github.com/fusioneng/shortcake-bakery/issues/33
Adds new pattern to `reversal` and `callback` functions to recognize Facebook video URL's in the pattern: `https://www.facebook.com/coreycf/videos/953479961370562/`
=> Add new acceptable pattern for FB embed/URL

inc/class-shortcake-bakery.php, shortcake-bakery.php
This means third-party code can extend `Shortcake_Bakery\Shortcodes\Shortcode` much earlier
=> Register autoloader as soon as the plugin is loaded

inc/shortcodes/class-shortcode.php, tests/class-shortcode.php, tests/test-shortcode.php
Expands the abstraction from `Shortcode::parse_iframes` so that it can be used to parse for other tags, like `<script`, in doing shortcode reversals.
=> Abstract `parse_iframes` to parse content for any arbitrary tag

inc/shortcodes/class-shortcode.php, tests/class-shortcode.php, tests/test-shortcode.php
It's more consistent with `parse_iframes()`
See #98
=> Rename `parse_script_tags()` to `parse_scripts()`

inc/shortcodes/class-abc-news.php, inc/shortcodes/class-flickr.php, inc/shortcodes/class-giphy.php, inc/shortcodes/class-guardian.php, inc/shortcodes/class-iframe.php, inc/shortcodes/class-infogram.php, inc/shortcodes/class-instagram.php, inc/shortcodes/class-livestream.php, inc/shortcodes/class-playbuzz.php, inc/shortcodes/class-rap-genius.php, inc/shortcodes/class-scribd.php, inc/shortcodes/class-script.php, inc/shortcodes/class-shortcode.php, inc/shortcodes/class-silk.php, inc/shortcodes/class-soundcloud.php, inc/shortcodes/class-videoo.php, inc/shortcodes/class-vimeo.php, inc/shortcodes/class-vine.php, inc/shortcodes/class-youtube.php, tests/class-shortcode.php, tests/test-shortcode.php, tests/test-silk-shortcode.php
The original problem to be solved was `parse_url()`'s lack of protocol-less URL support in PHP 5.3
Let's solve this specific problem, instead of half-solving it and introducing a new problem where the wrong protocol can be specified.
=> Deprecate `src_force_protocol` attribute in favor of 5.3 compat

inc/shortcodes/class-facebook.php
Registering and then calling `wp_enqueue_script()` doesn't do what we
need it to.
Fixes #146
=> Explicitly enqueue Facebook API script in the footer

inc/class-shortcake-bakery.php
This incorrect textdomain was my bug from #109 - fixing here so that translators can pick up this string where needed.
=> Fix incorrect textdomain in i18nized string

assets/js/build/shortcake-bakery-admin.js, assets/js/src/addEmbed/controller.js, inc/class-shortcake-bakery.php
When posting an inserted embed code to the Ajax endpoint, we should also
send the current post ID, so that it is available as additional context
to the "reversed_embed" action.
This also introduces a filter on "shortcake_bakery_embed_reversal", so
that it's possible to filter the result of reversing an embed code. The
idea is that this can be used to implement a system of protected embeds,
or some other way of handling embed codes which don't match one of the
defined post elements.
See #154.
=> Pass post ID into embed reversal endpoint, allow for filtering response

inc/class-shortcake-bakery.php
Gives the user the ability to add UI args to all shortcodes registered via Bakery or on a per-shortcode basis, without having to override the original class completely.
Rendering the new UI args can be handled by filtering `shortcake_bakery_shortcode_callback`.
=> Add filter for shortcode UI args for all bakery shortcakes

.editorconfig
Default `indent_size` was missing from `.editorconfig`.
See also https://github.com/wp-shortcake/image-shortcake/pull/64
=> Set default indent size to 4 spaces in EditorConfig

inc/shortcodes/class-instagram.php, tests/test-instagram-shortcode.php
This allows embeds from www.instagram.com to be rendered, rather than
only accepting the instagram.com domain.
#166
=> Allow for referencing instagram embed using subdomains

inc/shortcodes/class-abc-news.php, inc/shortcodes/class-flickr.php, inc/shortcodes/class-googledocs.php, inc/shortcodes/class-guardian.php, inc/shortcodes/class-iframe.php, inc/shortcodes/class-livestream.php, inc/shortcodes/class-pdf.php, inc/shortcodes/class-scribd.php, inc/shortcodes/class-script.php, inc/shortcodes/class-shortcode.php, inc/shortcodes/class-soundcloud.php, inc/shortcodes/class-videoo.php, inc/shortcodes/class-vimeo.php, inc/shortcodes/class-vine.php, inc/shortcodes/class-youtube.php
Fixes the plugin build by ensuring that it passes all new code-sniffs:
- Strict mode for `in_array()` comparisons.
- Use `Shortcode::parse_url()` instead of `parse_url()` for backcompat with PHP < 5.4
This also merges #179, because the error fixed there was causing errors in unit tests.
=> Fix PHPCS issues, errors in build

inc/shortcodes/class-googledocs.php
~ you say goodbye, I say hello
~ you say stop, and I say go
Fixes what what previously didn't even throw a warning, but is a fatal in PHP7.
See #178
=> Don't use `continue` when we mean `return`

inc/class-shortcake-bakery.php
The bakery scripts are getting enqueued on every admin page. The enqueue is failing since the `shortcode-ui` script is not registered/enqueued except when the editor is added to a page. Query Monitor reports this as a broken dependency.
=> Restrict enqueueing scripts to shortcode_ui_loaded_editor action

.travis.yml
Prevent duplicate builds from running on pull requests by only
triggering branch builds on master
=> Cut Travis' workload in half

inc/shortcodes/class-googledocs.php, tests/test-googledocs-shortcode.php
Extends the document types covered by this shortcode to include fusiontables visualizations.
Connected to #181
=> Add fusiontables support to [googledocs] shortcode

inc/shortcodes/class-facebook.php, tests/test-facebook-shortcode.php
Facebook has changed their embed post code to use iFrames, which won't get reversed by the `<script>` reversal detection. This adds support for the new format, while keeping support for the old.
Example of a new iFrame embed:
```
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Ffusionmedianetwork%2Fposts%2F1513457675346872&width=500" width="500" height="508" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
```
=> Add reversal support for Facebook's new iFrame-based embeds.

inc/shortcodes/class-scribd.php, tests/test-scribd-shortcode.php
Allows documents of the format https://www.scribd.com/document/320812028/Kansas-Maxmind-Complaint - the previous URL validation expected the slug `doc` only.
=> Add new allowed URL formats for Scribd post element

inc/shortcodes/class-iframe.php, inc/shortcodes/class-script.php, tests/test-iframe-shortcode.php, tests/test-script-shortcode.php
This makes it easy to retroactively apply HTTPS schemes to existing embeds when prepping a site to serve correctly over HTTPS.
=> Allow plugins to filter iFrame and Script embed sources.

inc/shortcodes/class-silk.php, tests/test-silk-shortcode.php
Since HTTPS is supported on Silk, let's make sure any Silk embeds use HTTPS so they work without other adjustments on HTTPS sites.
=> Force Silk embeds to use HTTPS URLs.

tests/bootstrap.php
Prevents ugly failures caused by the symlink in the test suite.
Since the test suite failures in #197 are caused by the symlink in the test setup and not anything in the plugin itself, defining the plugin dir correctly for tests seems like the best solution here. (If a user wants to register symlinks for their individual setup, they'll have to do something like this anyways, either by defining the whole plugin directory in a constant as this is doing, or by adding a filter to `plugins_url` or `plugin_basename`.)
=> Set WP_PLUGIN_DIR constant for tests

README.md, readme.txt
Triple-backticks don't mark a codeblock in the .org plugin directory. Fixing that here with the correct syntax (a single backtick on a line by itself before and after the code block in the readme.txt file, which gets converted to a tabbed section block in the README.md file.
=> Fix codeblock syntax in README for plugin directory 

composer.json
This allows users to easily [manage this plugin as a Composer dependency](https://roots.io/wordpress-plugins-with-composer/) in the same way that the main Shortcake plugin does.
Related to https://github.com/wp-shortcake/image-shortcake/pull/74
=> Define Composer `wordpress-plugin` package type

.travis.yml, composer.json, inc/class-asset-proxy.php, inc/class-shortcake-bakery.php, inc/shortcodes/class-abc-news.php, inc/shortcodes/class-facebook.php, inc/shortcodes/class-flickr.php, inc/shortcodes/class-giphy.php, inc/shortcodes/class-googledocs.php, inc/shortcodes/class-guardian.php, inc/shortcodes/class-iframe.php, inc/shortcodes/class-image-comparison.php, inc/shortcodes/class-infogram.php, inc/shortcodes/class-instagram.php, inc/shortcodes/class-live-photo.php, inc/shortcodes/class-livestream.php, inc/shortcodes/class-pdf.php, inc/shortcodes/class-playbuzz.php, inc/shortcodes/class-rap-genius.php, inc/shortcodes/class-scribd.php, inc/shortcodes/class-script.php, inc/shortcodes/class-shortcode.php, inc/shortcodes/class-silk.php, inc/shortcodes/class-soundcloud.php, inc/shortcodes/class-twitter.php, inc/shortcodes/class-videoo.php, inc/shortcodes/class-vimeo.php, inc/shortcodes/class-vine.php, inc/shortcodes/class-youtube.php, shortcake-bakery.php
The version of phpcodesniffer required by WPCS (^3.0.1) conflicted with
the pinned version of phpcs in composer.json. SInce phpcs is registered
as a dependency of wpcs, it makes sense to not pin it to a specific
version.
Also, PHP 5.3 isn't around anymore, and doesn't need to be included in
the Travis matrix.
=> Try to fix build by allowing latest version of PHPCS

inc/shortcodes/class-youtube.php, tests/test-youtube-shortcode.php
When trying to get a URL for a YouTube video, a logical place to look is
the "Share" link. The link provided if you click "Share", and then "Copy
URL", is a shortlink of the form `https://youtu.be/{embed_id}`.
This PR adds support for that url pattern to the Youtube post element.
=> Add support for YouTube short urls (youtu.be/xxxxxxxxxx)
